# The config recipe.
# The recipe defines the pipeline for processing user messages.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
assistant_id: 20231207-103006-several-gain

# Configuration for Rasa NLU (Natural Language Understanding).
# This part is responsible for understanding user inputs.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline: 
# The pipeline is a sequence of NLU components that process and interpret user messages.
# https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: WhitespaceTokenizer  # Splits the message into tokens based on whitespace.
  - name: RegexFeaturizer  # Uses regular expressions to help the model understand the message.
  - name: LexicalSyntacticFeaturizer  # Provides features based on lexical and syntactic analysis.
  - name: CountVectorsFeaturizer  # Converts tokens into a bag-of-words representation.
  - name: CountVectorsFeaturizer
    analyzer: char_wb  # Analyzes character n-grams to capture sub-word level information.
    min_ngram: 1  
    max_ngram: 4  
  - name: DIETClassifier
    epochs: 100  
    constrain_similarities: true 
  - name: EntitySynonymMapper  # Maps synonymous entity values to a common name.
  - name: ResponseSelector
    epochs: 100  
    constrain_similarities: true  


# Configuration for Rasa Core.
# This part is responsible for managing the flow of the conversation.
# https://rasa.com/docs/rasa/core/policies/
policies: 
# The policies guide how the bot decides on the next action in response to a user message.
  - name: MemoizationPolicy  # Remembers exact conversations and uses them to predict next actions.
  - name: UnexpecTEDIntentPolicy
    max_history: 10  
    epochs: 100  
  - name: TEDPolicy
    max_history: 5  # Maximum number of previous user messages to consider.
    epochs: 100  # Number of training epochs.
    constrain_similarities: true  
  - name: RulePolicy  # Allows defining rules for conversation flows.